### ISSUE TITLE
Alternate base urls no longer working

### ISSUE THREAD

**Issue by cmulk** [filebrowser/caddy#12]
When using an alternate baseurl (see example below), the filebrowser login page prompt no longer appears, with the loading animation just continuing forever. Looking at the page source, I can see that filebrowser is looking to load its javascript and css from the root base url "/static/...." instead of from the alternate base url "/admin/static/...". 

Example caddyfile:
```
:80 {
    root /site
    filemanager  /admin  /files
}
```

**Comment by 1138-4EB** [comment]
@cmulk, thanks for reporting! This is already fixed, but it won't be pushed to this repo until the next release. See filebrowser/filebrowser#522.

Meanwhile, you can build the frontend from sources and update `assets/rice-box.go` in this repo as explained in filebrowser/filebrowser#520.
