### ISSUE TITLE
Can't have aliases when using named database

### ISSUE THREAD

**Issue by Embraser01** [filebrowser/caddy#25]
**Are you asking for help with using Caddy or File Browser?**
No, I'd like to report a bug.

**When did you download File Browser from caddyserver.com?**
I just updated caddy today (including filebrowser)

**What is your entire Caddyfile?**

```text
alias1.example.com,
alias2.example.com {
	import "_presets/log.conf" # Just log requests
	import "_presets/ssl.conf" # Just the mail adress for ssl
	
	filebrowser / {
		database config.db
	}
}
```

**Description**
When starting the server it fails. I removed the named database and saw that there was two distinct databases created (one for alias1 and one for alias2).
When setting a name, both alias tries to access the same database and caddy just exit.

**Expected behaviour**
Caddy would start and both alias would use the same database.

**What is happening instead?**
Please, give full error messages and/or log.

When launching without named database:
```
Feb 13 20:23:33 mail caddy[32589]: [WARNING] A database is going to be created for your File Browser
Feb 13 20:23:33 mail caddy[32589]: instance at the following configuration:
Feb 13 20:23:33 mail caddy[32589]: Host:                 alias1.example.com
Feb 13 20:23:33 mail caddy[32589]: Path:
Feb 13 20:23:33 mail caddy[32589]: BaseURL:        /
Feb 13 20:23:33 mail caddy[32589]: It is highly recommended that you set the 'database' option to "aa9a1a8d169202e31f325f84660b0250.db".
Feb 13 20:23:34 mail caddy[32589]: [WARNING] A database is going to be created for your File Browser
Feb 13 20:23:34 mail caddy[32589]: instance at the following configuration:
Feb 13 20:23:34 mail caddy[32589]: Host:                 alias2.example.com,
Feb 13 20:23:34 mail caddy[32589]: Path:
Feb 13 20:23:34 mail caddy[32589]: BaseURL:        /
Feb 13 20:23:34 mail caddy[32589]: It is highly recommended that you set the 'database' option to "00223f07278b59f858203234c86eb75a.db".
```

When using named database:
```
Feb 13 20:22:44 mail systemd[1]: Started Caddy HTTP/2 web server.
Feb 13 20:22:44 mail caddy[32354]: Activating privacy features... 2019/02/13 20:22:44 [INFO][FileStorage:/etc/ssl/caddy] Started certificate maintenance routine
Feb 13 20:22:45 mail caddy[32354]: done.
Feb 13 20:22:45 mail systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Feb 13 20:22:45 mail systemd[1]: caddy.service: Unit entered failed state.
Feb 13 20:22:45 mail systemd[1]: caddy.service: Failed with result 'exit-code'.
```

**Additional context**
Before updating caddy, I tried to upgrade existing database bug got a timeout (https://github.com/filebrowser/filebrowser/issues/627)

but I finally manage to success by stopping caddy...

**How to reproduce?**
You should be able to reproduce the bug by using my caddyfile.

**Files**

N/A

**Comment by hacdias** [comment]
@Embraser01 BoltDB doesn't allow multiple connections to the database. What I think that is happening here is that it tries to open the database for each aliases and times out. I don't believe we can differentiate when we have aliases and we don't have them.

Please consider proxying the second alias to the the first one.

---

Although I think that with some work we could make this work without proxying I'm not sure.

**Comment by Embraser01** [comment]
Ok thanks! In this case I removed the alias because it was not necessary.

I don't know what changed between filebrowser@1 and filebrowser@2 as I don't fully understand Go, but It worked well before updating to v2. 

It would be nice to add a little note about this problem in the docs :wink:
