### ISSUE TITLE
how to change username and password?

### ISSUE THREAD

**Issue by unomind** [filebrowser/caddy#26]
How to change usrname and password? Digging your doc and not found.

here my Caddyfile:
```
domain.com:10022 {
  log stderr
  gzip
  tls off

  filebrowser / /home/user/caddy-filebrowser {
    database            /home/user/caddy-filebrowser/filebrowser.db
  }

}
```

Thanks

**Comment by hacdias** [comment]
You just need to login and then go to settings and change the password 😄 You can also manage users there so you can change your username.
