### ISSUE TITLE
panic: could not locate box "./frontend/dist"

### ISSUE THREAD

**Issue by dijiwiz** [filebrowser/caddy#8]
When I try to build from source for caddy I get the following error.

``` bash
panic: could not locate box "./frontend/dist"

Stack trace is:
github.com/GeertJohan/go%2erice.MustFindBox(0xb38c2e, 0xf, 0x86fc74)
        /home/hud/programs/gowork/src/github.com/GeertJohan/go.rice/box.go:110 +
0x7c
github.com/filebrowser/filebrowser.(*FileBrowser).Setup(0x11d995e0, 0x11d1fe00, 
0x12100a40)
        /home/hud/programs/gowork/src/github.com/filebrowser/filebrowser/filebrowser.go:132 +0x24
github.com/filebrowser/caddy/parser.Parse(0x11eaa410, 0xb012df, 0x4, 0x11d44520,
 0xb012df, 0x4, 0x11e76f8c, 0x1)
        /home/hud/programs/gowork/src/github.com/filebrowser/caddy/parser/parser
.go:263 +0x2fec
github.com/filebrowser/caddy/hugo.setup(0x11eaa410, 0x4, 0xb012df)
        /home/hud/programs/gowork/src/github.com/filebrowser/caddy/hugo/hugo.go:
42 +0x2c
github.com/mholt/caddy.executeDirectives(0x11db6380, 0xb14b59, 0x9, 0x191b3c0, 0
x42, 0x42, 0x1211be20, 0x1, 0x1, 0x0, ...)
        /home/hud/programs/gowork/src/github.com/mholt/caddy/caddy.go:666 +0x290
github.com/mholt/caddy.ValidateAndExecuteDirectives(0x1430d98, 0x11d1efc0, 0x11d
b6380, 0x11db6300, 0x1, 0x11d225c0)
        /home/hud/programs/gowork/src/github.com/mholt/caddy/caddy.go:622 +0x34c
github.com/mholt/caddy.startWithListenerFds(0x1430d98, 0x11d1efc0, 0x11db6380, 0
x0, 0x0, 0x0)
        /home/hud/programs/gowork/src/github.com/mholt/caddy/caddy.go:523 +0xe8
github.com/mholt/caddy.Start(0x1430d98, 0x11d1efc0, 0x1430d98, 0x11d1efc0, 0x0)
        /home/hud/programs/gowork/src/github.com/mholt/caddy/caddy.go:484 +0xc0
github.com/mholt/caddy/caddy/caddymain.Run()
        /home/hud/programs/gowork/src/github.com/mholt/caddy/caddy/caddymain/run
.go:162 +0x3e0
main.main()
        src/github.com/mholt/caddy/caddy/main.go:27 +0x20
```

Any ideas would be greatly appreciated. Thanks.

**Comment by 1138-4EB** [comment]
Hi @dijiwiz! Thanks for pointing this out. I suppose that you get the error when you execute/use the built `caddy`. You don't get any error at compile time, isn't it?

I think I know the source of this bug and I'll push a fix in a few minutes. I just want to make sure that our CI system didn't 'lie' when it told us that everything was ok: https://travis-ci.com/filebrowser/caddy/builds (note that the two most recent builds have nothing to do with this issue).

**Comment by dijiwiz** [comment]
Correct. No errors when it compiles but only when executing the complied
binary.

I just finished doing a go get -u github.com/filebrowser/caddy/hugo and
recompiled. I still get the same panic. Let me know how I might help.
Thanks for your quick reply.

**Comment by 1138-4EB** [comment]
You can either:

- Checkout branch `fix/rice-box-path` in `$GOPATH/src/github.com/filebrowser/caddy`.
- Download https://github.com/filebrowser/caddy/raw/fix/rice-box-path/assets/rice-box.go to `$GOPATH/src/github.com/filebrowser/caddy/assets/` (overwritting the existing one).
- Execute `sed -i 's#filebrowser/dist#frontend/dist#g' $GOPATH/src/github.com/filebrowser/caddy/rice-box.go`.
- Manually edit [`rice-box.go`](https://github.com/filebrowser/caddy/pull/9/files).

Then, just move to caddy's dir and try to build again.

**Comment by 1138-4EB** [comment]
@dijiwiz the fix is pushed to master now. Please, let us know if it works for you.

**Comment by dijiwiz** [comment]
It works. Thank you.

**Comment by 1138-4EB** [comment]
Hi @asialiugf! From your comment, it seems that your are not executing `rice embed-go` from `./lib`, but front `./frontend`. If so, you should add `cd ../lib` after `yarn build`. See https://github.com/filebrowser/filebrowser/blob/master/build/build_assets.sh.

Also, see filebrowser/filebrowser#520.

Last, if you are running filebrowser with a custom baseurl, you might need to checkout the latest version in `./frontend`. See filebrowser/filebrowser#522.

**Comment by asialiugf** [comment]
thank you for your response . 
sure I do "rice embed-go"  in the ./lib dir.   that is the result :: 

drwxrwxr-x. 2 charmi charmi      52 9月  15 17:23 bolt
-rw-rw-r--. 1 charmi charmi    2404 9月  15 17:23 doc.go
-rw-rw-r--. 1 charmi charmi   14866 9月  15 17:23 filebrowser.go
-rw-rw-r--. 1 charmi charmi   10500 9月  15 17:23 file.go
drwxrwxr-x. 2 charmi charmi    4096 9月  15 17:23 http
-rw-rw-r--. 1 charmi charmi 7276226 9月  16 16:37 rice-box.go
drwxrwxr-x. 2 charmi charmi      55 9月  15 17:23 staticgen

rice-box.go has being created  in ./lib dir.

and I am sure  the ./frontend  is state of the art.   downloaded from github.com/ like this
"  git clone --recurse-submodules https://github.com/filebrowser/filebrowser  "

unfortunately ,  the problem  is still  .

help me ! please.

**Comment by 1138-4EB** [comment]
`recurse-submodules` will not get the latest, but the commit which is tagged. In order to ensure you are using the latest, cd frontend, git fetch and git pull.

Also, you can open rice-box.go and check the path there.

Last, you can try the default procedure which is to execute `./build/build_all.sh` from filebrowser.

**Comment by hufh** [comment]
> `recurse-submodules` will not get the latest, but the commit which is tagged. In order to ensure you are using the latest, cd frontend, git fetch and git pull.
> 
> Also, you can open rice-box.go and check the path there.
> 
> Last, you can try the default procedure which is to execute `./build/build_all.sh` from filebrowser.

I tried all the methods and still failed to get it running. Could you please double check it? Thanks.

**Comment by 1138-4EB** [comment]
I just triggered all the builds in the CI environment, and all of them passed successfully: https://travis-ci.com/filebrowser

Please, try to reproduce your issue in a clean environment (either a docker container, a node in play-with-docker, a VM...) and provide the exact sequence of commands you are executing. That will help us reproduce it.

**Comment by hufh** [comment]
> I just triggered all the builds in the CI environment, and all of them passed successfully: https://travis-ci.com/filebrowser
> 
> Please, try to reproduce your issue in a clean environment (either a docker container, a node in play-with-docker, a VM...) and provide the exact sequence of commands you are executing. That will help us reproduce it.

@1138-4EB @asialiugf  I can get it compiled by running "./build/build_all.sh", but it can't run as expected with the same error: "panic: could not locate box "../frontend/dist", any thoughts?
